# Generated by Django 4.0.5 on 2022-07-01 21:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('author', models.TextField(blank=True, default='unknown user', editable=False, max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=200)),
                ('blog_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('thumbnail', models.URLField(max_length=400)),
                ('read_more', models.URLField(blank=True, max_length=400)),
                ('category', models.CharField(blank=True, max_length=10)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approve_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
    ]
